Add bus photos
metamorph-dev/karabus pull request #8
Opened 2023-07-25 11:04 UTC by metamorph-dev

2023-07-25 12:57 UTC, DenysMoskalenko requested changes

2023-07-25 12:57 UTC, DenysMoskalenko commented on app/apps/busses/views.py
> +            new_file.write(data)
Ты в транзакции начинаешь записывать файл, чем блокируешь таблицу для всех других на определенное время. В транзакции в идеале должно быть только взаимодействие с БД

2023-07-25 12:57 UTC, DenysMoskalenko commented on tests/test_busses.py
> +async def test_upload_bus_photo(ac: AsyncClient, session: AsyncSession) -> None:
Неудачные кейсы? Автобус может быть не найдет, может фотка быть какая-то не такая (если ты это учитываешь)

2023-07-25 13:29 UTC, metamorph-dev commented on app/apps/busses/views.py
> +            new_file.write(data)
Поправил

2023-07-25 13:30 UTC, metamorph-dev commented on tests/test_busses.py
> +async def test_upload_bus_photo(ac: AsyncClient, session: AsyncSession) -> None:
Поправил, дописал кейс на обновление автобуса, которого нет

2023-07-26 07:03 UTC, DenysMoskalenko commented on tests/test_busses.py
> +async def test_upload_bus_photo(ac: AsyncClient, session: AsyncSession) -> None:
Совет следующий, скачать что-нибдуь, что смотри покрытие, например coverage и делай так, чтоб оно было максимально большим 95% +. По началу будет лень, но доволньо быстро привыкнешь и начнешь писать много тестов на разные кейсы.
`coverage run -m pytest` - запустить
`coverage report` - посмотреть суммарный отчет в консоли
`coverage html ` - сгенерировать детальный отчет, где можно увидеть каждое место, которое ты не покрыл, на основе чего написать тест

2023-07-26 07:04 UTC, DenysMoskalenko approved these changes

2023-07-27 10:16 UTC, merged